### ISSUE TITLE
Uncaught error "FileNotFoundError", exiting the app.

### ISSUE THREAD

**Issue by 9acca9** [nickzuber/chs#18] opened 2021-03-06 20:18 UTC
I have that error when try to run from a raspbian.....
Thanks.

**Comment by BachoSeven** [comment] 2021-05-22 19:05
This is a duplicate of https://github.com/nickzuber/chs/issues/3, and can be closed since this has been fixed and [released](https://github.com/nickzuber/chs/releases/tag/v2.2.2) as well.

**Comment by nickzuber** [comment] 2021-05-27 15:25
Closing because a duplicate of #3 — I also released a new version recently, so hopefully that fixed it

**Closed by nickzuber** 2021-05-27 15:25 UTC
